# Node Exporter (1.1.2 is good. 1.2 causes crazy amount of log errors)
node_exporter_version: '1.1.2'
node_exporter_checksum: '8c1f6a317457a658e0ae68ad710f6b4098db2cad10204649b51e3c043aa3e70d'

# Promtail
promtail_version: 2.2.1
promtail_checksum: 40d8d414b44baa78c5010cb7575d74eea035b6b00adb78e9676a045d6730a16f
